### ISSUE TITLE
Change storage of Rdata files to TSV

### ISSUE THREAD

**Issue by cthoyt** [ps4dr/ps4dr#22]
It's impossible to look into these and see what's there. We need to make the file input/output more amenable to debugging by outputting as CSV or TSV and loading from those instead of using the R data loader. I understand this might result in making the scripts a bit slower, but it's worth it

**Comment by asifemon** [comment]
changing to CSV or TSV will increase the file size dramatically.

**Comment by cthoyt** [comment]
Fine, we can accept that since the reward is understandability.
