### ISSUE TITLE
Missing dependency in script 2.2

### ISSUE THREAD

**Issue by cthoyt** [ps4dr/ps4dr#24]
```2.2 Calculating Disease SPIAs

Error in library(org.Hs.eg.db) : 
  there is no package called ‘org.Hs.eg.db’
Execution halted
```
Is this because the dependency wasn't written on the readme?

**Comment by asifemon** [comment]
it's there in the description ..

**Comment by cthoyt** [comment]
Because I added it in 69bcb6efef57fd7511e876aab46dea383c4c38dd lol. Is that enough to solve the problem?
